const reality = [
  ['0','Inexistence sombre','Privation de sens, de relation et de lumière dans la cartographie philosophique.','Cadre philosophique'],
  ['1','Énergie fondamentale','Échelle subatomique : l’énergie est une grandeur physique à définir et mesurer.','Physique'],
  ['2','Matière incarnée','Corps et objets accessibles par les sens et par des mesures.','Physique'],
  ['3','Réalité médiatisée','Perception à travers un outil : écran, appel ou autre support.','Médiation'],
  ['4','Réalité enregistrée','Trace d’un événement passé, susceptible d’être rejouée ou modifiée.','Trace'],
  ['5','Réalité simulée','Apparence ou interaction produite par un système de simulation.','Simulation'],
  ['6','Réalité mentale','Images, mots et pensées intérieurs; leur existence ne garantit pas leur exactitude.','Expérience intérieure'],
  ['7','Réalité émotionnelle','Un sentiment vécu est réel comme expérience, sans établir automatiquement son interprétation.','Expérience intérieure'],
  ['8','Réalité onirique et symbolique','Rêves et symboles orientent parfois l’action; leur lecture demande du discernement.','Symbolique'],
  ['9','Discernement','Capacité de confronter apparence, ressenti, traces et cohérence dans le temps.','Philosophique / spirituel'],
  ['10','Lumière et observation','La lumière physique révèle; « lumière » porte aussi un sens psychologique et spirituel distinct.','Plusieurs registres'],
  ['11','Fréquence et vibration','Le son a des fréquences mesurables; les effets dépendent du système étudié.','Physique et interprétation'],
  ['12','Réalité ultime','Vérité divine dans le cadre théologique de l’auteur.','Théologique']
];
const numbers = [
  ['0','L’éternité','Potentiel et ouverture avant toute forme.'],['1','L’unité','Commencement, identité, point de départ.'],
  ['2','L’union','Relation, rencontre et reconnaissance de l’autre.'],['3','La trinité / la vie','Dynamique créatrice issue de la relation.'],
  ['4','La fondation','Structure, stabilité et ancrage.'],['5','Le chemin','Passage et expérience dans la structure.'],
  ['6','Le choix','Bifurcation et responsabilité.'],['7','L’intériorité','Retrait, réflexion et intégration.'],
  ['8','L’incarnation','Action alignée et retour dans le monde.'],['9','La plénitude','Cohérence provisoire avant un autre cycle.']
];
const workshops = [
  {id:'realites',stage:1,title:'Cartographier les réalités',question:'De quel mode d’existence parle-t-on?',status:'Carte philosophique',figure:'a01',other:['a13','plate-183'],caption:'Figure A1 · Échelle épistémique, Atlas-Mère p. 40',bench:'Explorer les niveaux 0 à 12',intro:'Sélectionnez un niveau. La cartographie nomme des domaines différents; elle ne les transforme pas en échelle physique unique.',type:'reality',claim:'Distinguer le mode d’existence d’une chose avant de juger sa vérité ou sa cause.',result:'Une vidéo, une pensée, un sentiment et un objet peuvent tous avoir des effets, sans relever du même domaine.',limit:'Les niveaux 0 à 12 constituent une taxonomie philosophique de travail, pas une loi cosmologique démontrée.',source:'Atlas-Mère, chapitres analytiques 01–02 (p. 7–8); Cartographie des 12 réalités, archive p. 184–189.',test:'Prolongement : décrire pour chaque cas le support, les sens mobilisés, le temps, l’interactivité et les traces conservées.'},
  {id:'energie',stage:2,title:'Quatre sens du mot énergie',question:'Que mesure-t-on lorsque le mot « énergie » change de domaine?',status:'Distinction conceptuelle',figure:'a02',other:['plate-205'],caption:'Figure A2 · Quatre sens du mot énergie, Atlas-Mère p. 42',bench:'Changer de registre',intro:'Passez d’un usage du mot à l’autre et examinez ce qui peut être mesuré.',type:'choices',options:[['physique','Physique','Énergie en joules : travail, chaleur, rayonnement. La mesure dépend du système et de l’instrument.'],['biologique','Biologique','Métabolisme et flux d’énergie dans un organisme. Variables possibles : calories, consommation d’oxygène.'],['neural','Neurobiologique','Activation d’un système nerveux. Variables possibles : fréquence cardiaque, conductance cutanée, activité cérébrale.'],['relation','Relationnel','Une personne peut décrire une relation comme « énergisante ». C’est d’abord un vécu et une métaphore tant que la variable n’est pas définie.']],claim:'Le même mot peut désigner une grandeur physique, un processus biologique, une activation et une expérience vécue.',result:'Un changement de vocabulaire ne donne pas une mesure commune à tous ces registres.',limit:'L’intensité d’un sentiment ne prouve aucune transmission d’énergie physique inconnue.',source:'Atlas-Mère, chapitre analytique 03 (p. 9), figure A2 p. 42; Document Maître V2, archive p. 146–182.',test:'Prolongement : formuler pour chaque proposition une variable observable, une unité et un instrument.'},
  {id:'reseau',stage:2,title:'Du neurone au réseau',question:'Qu’est-ce qui change quand des unités forment un ensemble?',status:'Simulation de réseau',figure:'a04',other:['a03','a19','a20','a21'],caption:'Figure A4 · Montée d’organisation, Atlas-Mère p. 46',bench:'Relier seize unités',intro:'Augmentez la densité des liens. Le dessin est un modèle de graphe; les nœuds ne sont pas des neurones réels.',type:'network',claim:'L’organisation des relations peut ajouter des propriétés au niveau du système.',result:'La taille du groupe connecté dépend des liens, et pas seulement du nombre d’unités.',limit:'Un réseau connecté ne suffit pas à démontrer la conscience ou à expliquer son mécanisme.',source:'Atlas-Mère, chapitres analytiques 04–05 (p. 10–11), figures A3–A4 et A19–A21.',test:'Prolongement : mesurer dans un vrai système les unités, les liens, les flux et une capacité fonctionnelle définie.'},
  {id:'analogies',stage:3,title:'Neurones, arbres et foule',question:'Qu’est-ce qui converge entre des réseaux très différents?',status:'Analogie trans-échelle',figure:'a05',other:['a06','a18'],caption:'Figure A5 · Neurones et arbres, Atlas-Mère p. 48',bench:'Comparer les mécanismes',intro:'Choisissez un domaine. Les formes analogues servent à poser des questions, puis on revient aux mécanismes propres à chacun.',type:'choices',options:[['neurone','Neurones','Signaux électrochimiques, synapses et circuits biologiques. Un neurone est une cellule spécialisée.'],['arbre','Arbres','Échanges chimiques et hydrauliques, réponses à l’environnement, interactions écologiques.'],['foule','Foule','Personnes, perception, communication, imitation, règles sociales et coordination collective.']],claim:'L’unité, la relation et l’organisation forment un vocabulaire comparatif utile à plusieurs échelles.',result:'Des motifs semblables peuvent apparaître dans des systèmes faits d’éléments différents.',limit:'La ressemblance des images ou des réseaux n’établit aucune identité de mécanisme entre neurone, arbre et foule.',source:'Atlas-Mère, chapitres analytiques 06–07 (p. 12–13), figures A5–A6 et A18; Dossier intégral et Manifeste en archives.',test:'Prolongement : définir séparément, pour chaque domaine, le signal, le lien, le temps de réponse et la capacité observée.'},
  {id:'intention',stage:4,title:'De l’intention à l’expérience',question:'Quelles étapes séparent une intention de l’effet ressenti?',status:'Modèle relationnel',figure:'a07',other:['a08','a09'],caption:'Figure A7 · Intention vers expérience, Atlas-Mère p. 52',bench:'Parcourir la chaîne',intro:'Activez chaque étape. Dans le cas V-01, une vidéo publique, un ressenti et une information ultérieure demandent des traces datées.',type:'choices',options:[['intention','1 · Intention','L’intention de l’autrice est rapportée plus tard. Sa formulation exacte au moment de créer la vidéo doit être documentée.'],['encodage','2 · Encodage','Des choix de mots, d’intonation, d’image et de contexte sont incorporés au message.'],['signal','3 · Signal','La vidéo transmet des sons et des images; elle constitue un canal perceptible.'],['reception','4 · Réception','Le récepteur perçoit, interprète et ressent avec sa mémoire, son contexte et ses attentes.'],['trace','5 · Trace','La chronologie distingue l’impression première de la confirmation ultérieure et de la relecture après coup.']],claim:'Une intention peut agir à travers des signes, une perception et une relation sans supposer d’emblée un canal inconnu.',result:'Chaque maillon de la chaîne peut être décrit et, pour certains, documenté ou mesuré.',limit:'Le cas V-01 ne démontre pas à lui seul une transmission non perceptible ou une télépathie.',source:'Atlas-Mère, chapitres analytiques 09–10 (p. 15–17), figures A7–A9; Recherche continue 01, cas V-01.',test:'Prolongement : horodater les impressions avant toute confirmation, contrôler les indices visibles et comparer des conditions à l’aveugle.'},
  {id:'temps',stage:5,title:'Temps, mémoire et trace',question:'Quel temps décrit-on : celui de l’événement, du corps, du vécu ou de l’information?',status:'Modèle à quatre registres',figure:'a12',other:['plate-226'],caption:'Figure A12 · Temps en quatre registres, Atlas-Mère p. 62',bench:'Changer de registre temporel',intro:'Un même récit peut être daté de plusieurs façons. Choisissez le registre qui organise votre observation.',type:'choices',options:[['physique','Physique','Temps des horloges et des événements datables. Il permet de fixer l’ordre des faits.'],['biologique','Biologique','Rythmes et changements d’un organisme, mesurables selon la variable choisie.'],['vecu','Vécu','Durée subjective : une minute peut sembler longue ou brève. C’est une donnée rapportée sur l’expérience.'],['informationnel','Informationnel','Une trace peut être stockée, copiée et revue longtemps après son événement d’origine.']],claim:'Le temps physique, biologique, vécu et informationnel ne répondent pas à la même question.',result:'Dater l’événement et dater son interprétation évite de réécrire la première impression après la découverte d’une information.',limit:'Une concordance découverte après coup ne prouve pas qu’une information future a causé une sensation passée.',source:'Atlas-Mère, chapitres analytiques 11 et 15 (p. 18 et 22), figure A12 p. 62; Recherche continue 01.',test:'Prolongement : garder des traces horodatées avant et après un événement, puis comparer les récits sans effacer leur version initiale.'},
  {id:'seuil',stage:5,title:'Accumulation, seuil et rupture',question:'Quand une variation graduelle produit-elle un changement visible?',status:'Modèle conceptuel',figure:'a10',other:['a11'],caption:'Figure A10 · Accumulation, seuil et transition, Atlas-Mère p. 58',bench:'Faire varier une accumulation',intro:'Déplacez le curseur. Le seuil affiché est choisi pour illustrer une transition; il ne vient pas d’une mesure biologique.',type:'threshold',claim:'Un système peut changer de régime lorsque des relations ou contraintes s’accumulent et franchissent une condition.',result:'Le modèle distingue accumulation continue et changement de catégorie au seuil choisi.',limit:'Le seuil et la forme de la courbe doivent être mesurés dans chaque domaine; une image ne suffit pas à les établir.',source:'Atlas-Mère, chapitres analytiques 12–13 (p. 19–20), figures A10–A11.',test:'Prolongement : mesurer une variable au fil du temps, définir le critère de transition et chercher des cas où la transition n’apparaît pas.'},
  {id:'cret',stage:6,title:'Le cycle CRET et EBSN',question:'Comment organiser une relation, ses transformations et ses traces?',status:'Architecture de travail',figure:'a14',other:['a16'],caption:'Figure A14 · CRET, Atlas-Mère p. 66',bench:'Suivre une transformation',intro:'Parcourez les fonctions du Cycle Relationnel d’Émergence Trans-échelle (CRET). EBSN sert à décrire l’architecture fédérée dans le corpus.',type:'choices',options:[['unite','1 · Unité','Définir ce qui entre en relation : personne, cellule, groupe ou information, selon le domaine.'],['relation','2 · Relation','Préciser le lien et son mécanisme : contact, signal, échange ou règle.'],['integration','3 · Intégration','Observer ce qui est combiné, conservé ou modifié dans le système.'],['transformation','4 · Transformation','Nommer une capacité ou une configuration nouvelle et la comparer à l’état initial.'],['trace','5 · Trace','Documenter ce qui persiste et peut influencer un cycle ultérieur.']],claim:'CRET offre une grille pour décrire unité, relation, intégration, transformation et trace à différentes échelles.',result:'Le cycle force à définir des variables et à conserver l’histoire du changement.',limit:'Une grille commune n’est pas une loi physique commune à tous les systèmes.',source:'Atlas-Mère, chapitres analytiques 23–24 (p. 31–32), figures A14 et A16; Document Maître V2.',test:'Prolongement : appliquer la grille à deux domaines, puis vérifier quelles variables et prédictions restent réellement comparables.'},
  {id:'nombres',stage:6,title:'Les nombres comme langage de sens',question:'Comment lire la séquence de 0 à 9 sans lui attribuer un pouvoir causal?',status:'Lecture symbolique',figure:'numerologie',other:['a13'],caption:'Discernement du réel · Chapitre 11, archive de l’Atlas-Mère p. 219',bench:'Parcourir les symboles 0 à 9',intro:'Choisissez un nombre pour voir son sens dans le livre. Cette carte est symbolique; elle ne prédit aucun événement.',type:'numbers',claim:'Les nombres mesurent dans un contexte scientifique et peuvent aussi organiser un récit symbolique.',result:'La séquence 0–9 propose des repères pour réfléchir à un cheminement humain.',limit:'Le nombre ne cause pas le réel, ne prédit pas l’avenir et ne remplace pas le discernement.',source:'Discernement du réel, chapitre 11 (archive de l’Atlas-Mère p. 219–220); Atlas-Mère, chapitre analytique 17 p. 24.',test:'Prolongement : utiliser le symbole pour formuler une question sur une décision, puis confronter cette question à des faits et à des conséquences observables.'},
  {id:'protocole',stage:7,title:'Mettre une hypothèse à l’épreuve',question:'Qu’est-ce qui pourrait confirmer, limiter ou contredire une proposition?',status:'Protocole expérimental',figure:'a15',other:['plate-29'],caption:'Figure A15 · Programme expérimental, Atlas-Mère p. 68',bench:'Construire un protocole RIM-01',intro:'Activez les conditions de base. Le dossier devient plus interprétable lorsqu’il prévoit aussi un résultat nul ou contraire.',type:'protocol',claim:'Une hypothèse gagne en valeur scientifique lorsqu’elle produit une prédiction distincte et accepte de pouvoir échouer.',result:'Pré-enregistrer les critères, contrôler les indices et conserver toutes les observations réduit les interprétations après coup.',limit:'Cocher ces étapes ne réalise pas l’expérience et ne constitue pas un résultat.',source:'Atlas-Mère, chapitre analytique 25 (p. 33), figure A15 p. 68; Recherche continue 01, protocole RIM-01.',test:'Prolongement : réaliser des essais consentis, garder les données brutes, analyser selon les critères fixés et publier aussi les résultats nuls.'},
  {id:'attention',stage:7,title:'Attention, technique et discernement',question:'Comment une interface influence-t-elle ce qu’on remarque et ce qu’on retient?',status:'Analyse des conditions',figure:'a17',other:['plate-226'],caption:'Figure A17 · Ce qui influence la conscience, Atlas-Mère p. 71',bench:'Examiner les conditions de lecture',intro:'Choisissez une condition. L’atelier compare des mécanismes possibles sans attribuer à une interface une cause universelle.',type:'choices',options:[['continu','Flux continu','Des contenus successifs sollicitent l’attention. Pour mesurer un effet, il faut définir la tâche et comparer des conditions.'],['pause','Pause et relecture','Une pause permet de dater une impression et de revenir au contenu avant une nouvelle interprétation.'],['source','Retour à la source','Ouvrir l’image avec sa légende et son passage évite de séparer le visuel de son contexte.'],['discussion','Discussion','Comparer des observations peut révéler des interprétations rivales, à condition de garder les traces initiales.']],claim:'L’attention, le support technique et le temps disponible modifient les conditions de lecture du réel.',result:'L’app peut rendre visibles ses propres sources, ses choix et ses incertitudes.',limit:'Une suggestion de bonne pratique n’est pas une mesure de son efficacité pour chaque personne.',source:'Atlas-Mère, chapitres analytiques 19–22 (p. 26–30), figure A17 p. 71; Discernement du réel, chapitres 13–19.',test:'Prolongement : comparer des tâches de lecture avec et sans pause, en mesurant compréhension et rappel selon un plan fixé à l’avance.'},
  {id:'synthese',stage:7,title:'Convergences et questions ouvertes',question:'Qu’est-ce que l’ensemble de la recherche permet de tenir, et que reste-t-il à tester?',status:'Synthèse du corpus',figure:'a16',other:['a13','plate-256'],caption:'Figure A16 · Nouvel algorithme naturel, Atlas-Mère p. 70',bench:'Lire les niveaux de conclusion',intro:'Choisissez un niveau de conclusion pour garder les acquis, les analogies et les questions ouvertes à leur juste place.',type:'choices',options:[['etabli','Ce qui est observable','Les médias transportent de l’information; les organismes répondent à des signaux selon leurs mécanismes; les traces changent les lectures ultérieures.'],['modele','Modèles de travail','Relation, intégration, changement et trace aident à organiser des comparaisons si chaque variable est définie.'],['analogie','Analogies','Des architectures peuvent se ressembler entre neurones, plantes et foules, sans fonctionner de manière identique.'],['ouvert','À mettre à l’épreuve','Une intention produit-elle un effet différentiel au-delà du contenu perceptible et des attentes? Le corpus ne l’établit pas encore.'],['sens','Sens philosophique','Amour, Source, nombres et discernement forment des lectures de sens clairement distinguées des résultats de laboratoire.']],claim:'La recherche gagne en cohérence lorsque les résultats établis, les modèles, les analogies et les propositions de sens restent traçables.',result:'Le parcours mène à des questions plus précises, des expériences possibles et une lecture responsable du corpus.',limit:'La convergence de plusieurs documents qui reprennent une même source ne constitue pas plusieurs réplications indépendantes.',source:'Atlas-Mère, matrice de convergence p. 35, registre des effets p. 36, hypothèses p. 37 et figure A16 p. 70.',test:'Prolongement : tenir un registre public versionné des propositions, sources, observations et corrections.'}
];

const gallery = [
  {id:'cover',title:'Atlas-Mère des recherches · couverture',page:1,type:'Couverture'},
  {id:'atlas-interlude',title:'Ouverture de l’atlas visuel commenté',page:39,type:'Page de section'},
  ...['Échelle épistémique','Quatre sens du mot énergie','Organisation de la conscience','Montée d’organisation','Neurones et arbres','Comparatif biologique neurones/arbres','Intention vers expérience','Convergence de la conscience intentionnelle','Neurochimie sociale','Accumulation, seuil et transition','Différenciation et engendrement','Temps en quatre registres','Discernement','CRET','Programme expérimental','Nouvel algorithme naturel','Ce qui influence la conscience','De l’humain à la foule','Anatomie d’un neurone','Formes de neurones','Deux neurones connectés'].map((title,i)=>({id:`a${String(i+1).padStart(2,'0')}`,title,page:[40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,71,73,75,77,79][i],type:'Figure commentée'})),
  ...[[6,'Cartographier les registres du réel'],[17,'Le vivant et ses architectures'],[29,'Hypothèses et méthode'],[38,'Atlas visuel commenté'],[81,'Programme de travail'],[85,'Les archives de la recherche'],[119,'Manifeste : conscience et relation'],[145,'Document maître intégral'],[183,'Cartographie des douze réalités'],[190,'Discernement du réel'],[205,'Du sentiment au sens'],[226,'Attention et temps long'],[256,'Atelier de transmission']].map(([page,title])=>({id:`plate-${page}`,title,page,type:'Interlude conceptuel'})),
  {id:'numerologie',title:'Les nombres de 0 à 9 dans Discernement du réel',page:219,type:'Page du livre'},
  ...[89,91,93,95,97,99,101,103,105,107,109,131,132,133,134,135,136,137,138,139,140,141,146,147,149,152,153,154,156,157,159,161,163,165,166,168,170,171,173,174,179,180,181].map(page=>({id:`archive-${page}`,title:page<120?'Dossier intégral : image et recherche':page<145?'Manifeste : image et recherche':'Document maître : page illustrée',page,type:'Archive visuelle'}))
];
const asset=id=>`./assets/${id}.webp`;
const $=s=>document.querySelector(s);
const state={index:0,figureOffset:0,choice:0,view:'workshop'};
const safeLoad=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let notes=safeLoad('meyden-lab-notes-v1',{}),completed=safeLoad('meyden-lab-completed-v1',{});
function saveLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function svgElement(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,String(v)));return e}
function text(parent,tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;parent.append(el);return el}
function renderNav(){const list=$('#workshop-list');list.replaceChildren();workshops.forEach((w,i)=>{const b=document.createElement('button');b.type='button';b.className='workshop-button'+(i===state.index&&state.view==='workshop'?' active':'')+(completed[w.id]?' complete':'');b.setAttribute('aria-current',i===state.index&&state.view==='workshop'?'step':'false');const n=text(b,'span',String(i+1).padStart(2,'0'),'workshop-number');text(b,'span',w.title);b.addEventListener('click',()=>openWorkshop(i));list.append(b)});$('#progress-label').textContent=`${Object.keys(completed).filter(k=>completed[k]).length} / ${workshops.length} ateliers`}
function openWorkshop(i){state.index=Math.max(0,Math.min(workshops.length-1,i));state.choice=0;state.figureOffset=0;state.view='workshop';$('#gallery-view').hidden=true;$('#workshop-view').hidden=false;$('#gallery-button').textContent='Atlas des images';renderWorkshop();renderNav();window.scrollTo({top:0,behavior:'smooth'})}
function renderWorkshop(){const w=workshops[state.index];$('#workshop-eyebrow').textContent=`Passage ${w.stage} sur 7 · Atelier ${state.index+1} sur ${workshops.length}`;$('#workshop-title').textContent=w.title;$('#workshop-question').textContent=w.question;$('#status-badge').textContent=w.status;$('#bench-title').textContent=w.bench;$('#bench-intro').textContent=w.intro;$('#claim').textContent=w.claim;$('#result').textContent=w.result;$('#limit').textContent=w.limit;$('#source').textContent=w.source;$('#test').textContent=w.test;$('#figure-image').src=asset(w.figure);$('#figure-image').alt=w.caption;$('#figure-caption').textContent=w.caption;$('#other-figure').hidden=!w.other?.length;$('#note').value=notes[w.id]||'';$('#note-status').textContent='';$('#complete').textContent=completed[w.id]?'Atelier terminé ✓':'Terminer l’atelier';$('#complete').classList.toggle('done',!!completed[w.id]);$('#previous').disabled=state.index===0;$('#next').disabled=state.index===workshops.length-1;renderBench(w)}
function renderBench(w){const controls=$('#controls'),exp=$('#experiment'),flow=$('#lab-flow');controls.replaceChildren();exp.replaceChildren();flow.replaceChildren();flow.hidden=w.type!=='network';if(w.type==='reality')return renderReality(controls,exp);if(w.type==='numbers')return renderNumbers(controls,exp);if(w.type==='network')return renderNetwork(controls,exp,flow);if(w.type==='threshold')return renderThreshold(controls,exp);if(w.type==='protocol')return renderProtocol(controls,exp);renderChoices(w,controls,exp)}
function buttons(controls,items,onSelect){const group=document.createElement('div');group.className='controls';group.setAttribute('role','group');group.setAttribute('aria-label','Options de l’atelier');const bs=items.map(([key,label],i)=>{const b=document.createElement('button');b.type='button';b.className='option-button';b.textContent=label;b.setAttribute('aria-pressed',String(i===0));b.addEventListener('click',()=>{bs.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));onSelect(i)});group.append(b);return b});controls.append(group)}
function renderChoices(w,controls,exp){buttons(controls,w.options,i=>show(i));function show(i){exp.replaceChildren();const [key,label,desc]=w.options[i];text(exp,'h3',label);text(exp,'p',desc);text(exp,'p','Question à garder : quelle trace ou mesure distinguerait cette lecture d’une autre?','small')}show(0)}
function renderReality(controls,exp){buttons(controls,reality.map(r=>[r[0],r[0]]),i=>show(i));function show(i){exp.replaceChildren();const [n,title,desc,kind]=reality[i];text(exp,'span',n,'reality-index');text(exp,'h3',title);text(exp,'p',desc);text(exp,'p',`Registre : ${kind}. La cartographie sert d’outil de discernement. Elle n’établit pas une progression expérimentale du niveau 0 au niveau 12.`,'small')}show(0)}
function renderNumbers(controls,exp){buttons(controls,numbers.map(n=>[n[0],n[0]]),i=>show(i));function show(i){exp.replaceChildren();const [n,title,desc]=numbers[i];text(exp,'span',n,'number-symbol');text(exp,'h3',title);text(exp,'p',desc);text(exp,'p','Usage : symbole de réflexion, jamais outil de prédiction.','small')}show(0)}
function rangeControl(controls,label,min,max,value,format,onInput){const wrap=document.createElement('label');wrap.className='range-control';const heading=document.createElement('span');const val=document.createElement('strong');heading.textContent=label+' · ';heading.append(val);const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.value=value;wrap.append(heading,input);controls.append(wrap);function update(){val.textContent=format(+input.value);onInput(+input.value)}input.addEventListener('input',update);update()}
function renderNetwork(controls,exp,flow){
  let density=19,prediction=null;
  flow.innerHTML='<span>1 · Prédire</span><span>2 · Manipuler</span><span>3 · Comparer</span>';
  const prompt=text(controls,'p','À 19 % de liens possibles, combien des 16 unités seront dans le plus grand groupe connecté?','lab-prompt');
  const choices=document.createElement('div');choices.className='prediction-choices';choices.setAttribute('role','group');choices.setAttribute('aria-label','Votre prédiction');
  const categories=[['petit','1 à 5 unités'],['moyen','6 à 12 unités'],['grand','13 à 16 unités']];
  const choiceButtons=categories.map(([key,label])=>{const b=document.createElement('button');b.type='button';b.className='option-button';b.textContent=label;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{prediction=key;choiceButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));reset()});choices.append(b);return b});controls.append(choices);
  const run=document.createElement('button');run.type='button';run.className='run-experiment';run.textContent='Lancer l’expérience';run.addEventListener('click',draw);
  rangeControl(controls,'Densité visée',0,100,density,v=>`${v} %`,v=>{density=v;reset()});
  controls.append(run);
  function reset(){prompt.textContent=`À ${density} % de liens possibles, combien des 16 unités seront dans le plus grand groupe connecté?`;run.disabled=!prediction;exp.replaceChildren();text(exp,'h3','Votre hypothèse');text(exp,'p',prediction?`Vous prévoyez ${categories.find(x=>x[0]===prediction)[1]} dans le plus grand groupe. Lancez l’expérience pour voir le résultat.`:'Choisissez une prédiction avant de révéler le réseau.');text(exp,'p','Vous pouvez changer la densité visée avant chaque essai.','small')}
  function draw(){if(!prediction)return;exp.replaceChildren();const svg=svgElement('svg',{viewBox:'0 0 500 215',role:'img','aria-label':'Réseau de seize unités et leurs liens'});const pts=Array.from({length:16},(_,i)=>[250+166*Math.cos(i*Math.PI/8-.7),108+82*Math.sin(i*Math.PI/8-.7)]);const adj=Array.from({length:16},()=>[]);let edges=0;
    for(let i=0;i<16;i++)for(let j=i+1;j<16;j++){const h=(((i+1)*92821+(j+1)*68917+(i+1)*(j+1)*2311)%100003)/100003;if(h<density/100){edges++;adj[i].push(j);adj[j].push(i);svg.append(svgElement('line',{x1:pts[i][0],y1:pts[i][1],x2:pts[j][0],y2:pts[j][1],stroke:'#976c4a','stroke-width':1.3,'stroke-opacity':.7}))}}
    let visited=new Set(),largest=0;for(let i=0;i<16;i++){if(visited.has(i))continue;const stack=[i];visited.add(i);let size=0;while(stack.length){const u=stack.pop();size++;for(const v of adj[u])if(!visited.has(v)){visited.add(v);stack.push(v)}}largest=Math.max(largest,size)}
    pts.forEach(([x,y],i)=>svg.append(svgElement('circle',{cx:x,cy:y,r:7,fill:adj[i].length?'#ec8746':'#7c9280'})));
    const actual=largest<=5?'petit':largest<=12?'moyen':'grand';text(exp,'h3',prediction===actual?'Votre prédiction correspond au modèle':'Le modèle donne un autre résultat');exp.append(svg);text(exp,'p',`${edges} liens sur 120 possibles; plus grand groupe : ${largest} unités sur 16.`);text(exp,'p',`Calcul : 16 × 15 ÷ 2 = 120 paires possibles. Densité obtenue : ${(edges/120*100).toFixed(1).replace('.',',')} %. Votre prédiction : ${categories.find(x=>x[0]===prediction)[1]}.`,'small');text(exp,'p','Que se passe-t-il si vous réduisez la densité puis refaites une prédiction? Notez votre observation dans le carnet.','small');text(exp,'p','Les liens suivent une règle fixe pour comparer les essais. Ce graphe est un modèle; il ne mesure ni neurones réels ni conscience.','small')}
  reset();
}
function renderThreshold(controls,exp){rangeControl(controls,'Accumulation',0,100,25,v=>`${v} / 100`,draw);function draw(v){exp.replaceChildren();text(exp,'h3',v<60?'Avant le seuil illustratif':'Au-delà du seuil illustratif');const svg=svgElement('svg',{viewBox:'0 0 500 190',role:'img','aria-label':'Courbe conceptuelle avec seuil à 60'});svg.append(svgElement('line',{x1:35,y1:155,x2:475,y2:155,stroke:'#829083'}));svg.append(svgElement('line',{x1:35,y1:155,x2:35,y2:20,stroke:'#829083'}));svg.append(svgElement('line',{x1:299,y1:22,x2:299,y2:155,stroke:'#b7a089','stroke-dasharray':'5 5'}));svg.append(svgElement('path',{d:'M35 143 C95 140 180 128 259 110 C284 105 298 100 303 66 C310 41 390 34 475 31',fill:'none',stroke:'#ef8a49','stroke-width':3}));svg.append(svgElement('circle',{cx:35+v*4.4,cy:v<60?143-(v/60)*43:66-(v-60)/40*35,r:7,fill:'#fff1df'}));const label=svgElement('text',{x:303,y:176,fill:'#dbb192','font-size':12,'text-anchor':'middle'});label.textContent='seuil choisi';svg.append(label);exp.append(svg);text(exp,'p',v<60?'Le paramètre s’accumule; la transition du modèle n’est pas franchie.':'La condition choisie est franchie; le modèle affiche un autre régime.');text(exp,'p','Courbe et seuil sont illustratifs, sans données empiriques.','small')}}
function renderProtocol(controls,exp){const conditions=[['prediction','Prédiction écrite avant les essais'],['controle','Condition témoin et indices contrôlés'],['aveugle','Réponses consignées avant révélation'],['analyse','Critère d’analyse fixé à l’avance'],['null','Résultat nul conservé']];const selected=new Set();conditions.forEach(([id,label])=>{const b=document.createElement('button');b.className='option-button';b.type='button';b.textContent=label;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{if(selected.has(id))selected.delete(id);else selected.add(id);b.setAttribute('aria-pressed',String(selected.has(id)));show()});controls.append(b)});function show(){exp.replaceChildren();text(exp,'h3',`${selected.size} / ${conditions.length} conditions préparées`);const box=document.createElement('div');box.className='steps';conditions.forEach(([id,label])=>{const row=document.createElement('div');row.className='step';text(row,'b',(selected.has(id)?'✓ ':'○ ')+label);box.append(row)});exp.append(box);text(exp,'p','Il reste à définir les participants, la mesure, le nombre d’essais, le consentement et la procédure détaillée.','small')}show()}
function galleryView(){state.view='gallery';$('#workshop-view').hidden=true;$('#gallery-view').hidden=false;$('#gallery-button').textContent='Retour aux ateliers';renderNav();window.scrollTo({top:0,behavior:'smooth'});if($('#gallery-grid').children.length)return;const grid=$('#gallery-grid');gallery.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='gallery-item';const img=document.createElement('img');img.src=asset(item.id);img.alt=item.title;img.loading='lazy';b.append(img);const cap=document.createElement('span');cap.textContent=item.title;const small=document.createElement('small');small.textContent=`${item.type} · Atlas-Mère p. ${item.page}`;cap.append(small);b.append(cap);b.addEventListener('click',()=>openImage(item.id,`${item.title} · Atlas-Mère p. ${item.page}`));grid.append(b)})}
function openImage(id,caption){$('#dialog-image').src=asset(id);$('#dialog-image').alt=caption;$('#dialog-caption').textContent=caption;$('#image-dialog').showModal()}
$('#gallery-button').addEventListener('click',()=>state.view==='gallery'?openWorkshop(state.index):galleryView());$('#close-dialog').addEventListener('click',()=>$('#image-dialog').close());$('#image-dialog').addEventListener('click',e=>{if(e.target===$('#image-dialog'))$('#image-dialog').close()});$('#image-button').addEventListener('click',()=>{const w=workshops[state.index];const id=state.figureOffset===0?w.figure:w.other[state.figureOffset-1];openImage(id,$('#figure-caption').textContent)});$('#other-figure').addEventListener('click',()=>{const w=workshops[state.index];state.figureOffset=(state.figureOffset+1)%(1+w.other.length);const id=state.figureOffset===0?w.figure:w.other[state.figureOffset-1];const item=gallery.find(x=>x.id===id);$('#figure-image').src=asset(id);$('#figure-image').alt=item?.title||w.caption;$('#figure-caption').textContent=item?`${item.title} · Atlas-Mère p. ${item.page}`:w.caption});$('#note').addEventListener('input',()=>{const id=workshops[state.index].id;notes[id]=$('#note').value;$('#note-status').textContent=saveLocal('meyden-lab-notes-v1',notes)?'Brouillon enregistré':'Stockage indisponible'});$('#save-note').addEventListener('click',()=>{const id=workshops[state.index].id;notes[id]=$('#note').value;$('#note-status').textContent=saveLocal('meyden-lab-notes-v1',notes)?'Observation enregistrée':'Stockage indisponible'});$('#complete').addEventListener('click',()=>{const id=workshops[state.index].id;notes[id]=$('#note').value;completed[id]=true;const ok1=saveLocal('meyden-lab-notes-v1',notes),ok2=saveLocal('meyden-lab-completed-v1',completed);renderNav();renderWorkshop();$('#note-status').textContent=ok1&&ok2?'Progression enregistrée':'Stockage indisponible'});$('#previous').addEventListener('click',()=>openWorkshop(state.index-1));$('#next').addEventListener('click',()=>openWorkshop(state.index+1));openWorkshop(0);
